services:
  excalidraw:
    image: qallpa-excalidraw:1.0.0
    container_name: qallpa-excalidraw
    restart: unless-stopped
    ports:
      - "8095:3030"
    volumes:
      - excalidraw-data:/app/data
    networks:
      - default
      - proxy-network

volumes:
  excalidraw-data:

networks:
  proxy-network:
    external: true
